import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Footer from "@/components/Footer";
import ConvexClientProvider from "@/components/providers/ConvexClientProvider";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});
export const metadata: Metadata = {
  title: "Code Crafter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={` ${inter.className} antialiased min-h-screen bg-white text-gray-900 dark:bg-gradient-to-b dark:from-[#1a1a1a] dark:to-[#0f0f0f] dark:text-gray-100 flex-col`}
        >
          <ConvexClientProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {/* <Header /> */}
              {children}
              <Toaster position="bottom-right" reverseOrder={false} />
            </ThemeProvider>
          </ConvexClientProvider>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
